[Service]
Environment=COUPONLEO_DIRECT_QUERY_MODE=true
Environment=COUPONLEO_WARM_SNAPSHOT=false
Environment=COUPONLEO_API_HOST=127.0.0.1
Environment=COUPONLEO_API_PORT=9600
Environment=COUPONLEO_API_DEBUG=false
